services:
  - type: web
    name: testeon-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app_firebase:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FIREBASE_PRIVATE_KEY_ID
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_CLIENT_ID
        sync: false
      - key: FIREBASE_CLIENT_X509_CERT_URL
        sync: false 